[FE-15602] Popup image support
heavyai/heavyai-charting pull request #650
Opened 2023-07-10 19:56 UTC by johallar

# Merge Checklist
## :wrench: Issue(s) fixed:
- [ ] Author referenced issue(s) fixed by this PR:
- [ ] Fixes #0

## :smoking: Smoke Test
- [ ] Works in chrome
- [ ] Works in firefox
- [ ] Works in safari
- [ ] Works in ie edge
- [ ] Works in ie 11

## :ship: Merge
- [ ] author crafted PR's title into release-worthy commit message.

2023-07-17 15:45 UTC, cmatzenbach requested changes
Only one area where changes needed - everything else works well and code looks good

2023-07-17 22:29 UTC, johallar commented on src/mixins/raster-layer.js
> +  const imageExtensions = [
👍 Changes made whenever you can take another look

2023-07-18 17:26 UTC, johallar commented
I'm going to make one update here to handle query string parameters w image previews. Current check is a little too dumb `endsWith`, and sounds like some use cases will need to be able to parse image names with query string params after.

2023-07-18 18:26 UTC, johallar commented
OK @cmatzenbach, made an update to parse URLs a little smarter so we can handle query string params and more. At your earliest convenience

2023-07-18 19:01 UTC, cmatzenbach approved these changes
LGTM

2023-07-18 19:14 UTC, johallar commented on src/mixins/raster-layer.js
> +  function filenameHasExtension(filename, extensions) {
Fixed this up [here](https://github.com/heavyai/heavyai-charting/pull/650/files#diff-17533c14138ae3b018fdbf3302ac845357e33c691349841654b30d2566e6be24R453)

2023-07-18 20:22 UTC, merged